### ISSUE TITLE
Customizable Buttons [Suggestion]

### ISSUE THREAD

**Issue by Tiberion000** [experiment322/controlloid-server#1]
I used the app, and it's nice and functional. Easy to use, too.
The issue I have is when playing on other systems.

This can be easily solved for the GameBoy Advanced games, using only D-pad and replace some buttons. But the N64, for example, uses 4 buttons for D-Pad, 4 buttons for C-buttons, more buttons, you get it.

Maybe add something so users can add custom buttons for their games?

**Comment by experiment322** [comment]
I'm not sure if I understand the problem.
The example you gave, the N64 controller, has less buttons than the application can handle. And I guess you use an N64 emulator which lets you remap the controls. Then a possible mapping would be:
* star

**Comment by experiment322** [comment]
@Tiberion000, did the previous comment solved your issue?
