### ISSUE TITLE
Buttons not working as expected

### ISSUE THREAD

**Issue by rgarrigue** [experiment322/controlloid-server#2]
Hi

Just tried controlloid on Ubuntu 18.04 with Fell's Seal, a tactical RPG. Here's a screenshot of the control mapping from the game

![image](https://user-images.githubusercontent.com/1872031/57209001-e65c3d80-6fd6-11e9-95e9-579cacea1188.png)

My issue is, it's not working as expected. 
- Bottom arrow is left
- Left arrow is right
- Right is up
- Up is nothing (I could identify)
- Right stick is working OK except for the left, which result in nothing
- Left stick is not working, except for the left which is start
- Triangle is X
- Cross is A
- Square is Y
- < is LB > is RB as I'ld expect
- >> is start
- << is - (back)
- - is start  
- Start is nothing

No log whatsoever in server console.

How can I fix that ? 

A quick suggestion even after it's fixed, add a mapping cross/square/round/triangle <=> ABXY in the README :)

Anyway thanks, it's working seamlessly except for this.

**Comment by rgarrigue** [comment]
Hmm looking for a way to remap, I see this https://www.reddit.com/r/Ubuntu/comments/941f9i/bad_gamepad_mapping_in_ubuntu_1804/. Might not be you. If you know of any remapping UI I'ld be glad to hear.

**Comment by rgarrigue** [comment]
I tried gamepad-tool, didn't worked out, it didn't changed the mapping in game, even after restarting etc. For further reference here's the log (which include link for the tool)

```
SDL2 Gamepad Tool v1.2 by General Arcade (compiled with SDL version 2.0.7, DLL version 2.0.8)
Website: http://generealarcade.com/gamepadtool/

Searching gamepads...
Found 1 gamepad(s):
"controlloid-192.168.0.16", 00000000636f6e74726f6c6c6f696400
Environment variable "SDL_GAMECONTROLLERCONFIG" is not defined
Checking if new mappings available from github: https://github.com/gabomdq/SDL_GameControllerDB
Mapping string: '00000000636f6e74726f6c6c6f696400,controlloid one,platform:Linux,a:b0,b:b1,x:b3,y:b2,back:b8,start:b9,leftshoulder:b4,rightshoulder:b5,dpup:b10,dpdown:b11,dpleft:b12,dpright:b13,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,'
Searching gamepads...
Found 1 gamepad(s):
"controlloid one", 00000000636f6e74726f6c6c6f696400 (mapping available)
Setting environment variable "SDL_GAMECONTROLLERCONFIG" to "00000000636f6e74726f6c6c6f696400,controlloid one,platform:Linux,a:b0,b:b1,x:b3,y:b2,back:b8,start:b9,leftshoulder:b4,rightshoulder:b5,dpup:b10,dpdown:b11,dpleft:b12,dpright:b13,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,"
```

**Comment by rgarrigue** [comment]
And here's the mapping as outputed by jstest-gtk `apt install jstest-gtk` on Ubuntu 18.04. Seems legit.

![image](https://user-images.githubusercontent.com/1872031/57211312-19ef9580-6fe0-11e9-9405-47288ec64d98.png)

**Comment by rgarrigue** [comment]
Okay, found the issue. As I though this was on the game side, I binded some keyboard's key, which screwed up the gamepad.

**Comment by experiment322** [comment]
I'm glad you discovered the issue and managed to solve it.

I've been notified that it doesn't work with PCSXR (for example), but I didn't have time to test it. If somebody comes across this issue they might want to try using some software that maps controllers events to key presses. Two of them are [antimicro](https://github.com/AntiMicro/antimicro) and [QJoyPad](http://qjoypad.sourceforge.net/).

I'll try to add some instructions for linux too in the close future (after some testing and research).
