### ISSUE TITLE
Phone is not able to connect to server

### ISSUE THREAD

**Issue by Edison-f** [experiment322/controlloid-server#4]
This is what the console outputs whenever I try to connect, I have assigned all the buttons and sticks already,

te:' ip ' command:'.\bin\ws_handler.exe' origin:'http:// ip :31415' | CONNECT
Wed, 22 May 2019 12:01:30 -0700 | ERROR  | stderr     | url:'http://ip:31415/' id:'1558551690549662800' remote:'ip' command:'.\bin\ws_handler.exe' origin:'http://ip:31415' pid:'5172' | error: no vjoy device available or none with valid configuration (16 BTN, X, Y, RX, RY)
Wed, 22 May 2019 12:01:30 -0700 | ACCESS | session    | url:'http://ip:31415/' id:'1558551690549662800' remote:'ip' command:'.\bin\ws_handler.exe' origin:'http://ip:31415' pid:'5172' | DISCONNECT

**Comment by experiment322** [comment]
Did you let the setup finish? You can try to uninstall vJoy and run the server again. It will detect that it's missing and setup the driver and joysticks again. Please be patient.

**Comment by experiment322** [comment]
Apparently, there was an issue if the script ran from a different drive besides `C:`. Maybe that was your issue too. I've pushed a fix now, re-download the server and try to run the fixed version.

**Comment by experiment322** [comment]
Does it work now?

**Comment by Edison-f** [comment]
Yes it works perfectly now, thanks.

**Comment by experiment322** [comment]
Ok, then I'll close this issue.

**Comment by icarito** [comment]
Just a note that on Linux (Arch) I had to `modprobe uinput` for this to work. Might want to add that to the README.
Thanks!
